### PR TITLE
Update package.py

### PR DESCRIPTION
**Pull request by rashawnLK**
Fix typo in description and remove blank line in description.

### CODE REVIEW

**Comment by mwkrentel** [comment]
@rashawnLK It's not the blank line.  I know other packages with blank lines.

I think this is a python 2 vs python 3 thing over the use of unicode.
If it's Ok with you, I'll just replace the unicode with (R).
Nothing can complain about that.

**Comment by rashawnLK** [comment]
That is okay with me and seems like the reasonable thing to do.

Thank you,

-Rashawn

**Comment by mwkrentel** [comment]
I pushed up a commit that changed unicode to (R) and left in the blank line.
It now passes the test that previously failed.

So, I'll close this.   You probably want to make a fork of the main spack, not mine.

**Comment by rashawnLK** [comment]
@mwkrentel , thank you for your assistance. I will create new forks going forward.

**Pull request closed without merging**
